services:

  bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: swipe_bot
    restart: always
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: swipe_redis
    restart: always
    ports:
      - "6380:6379"
